# Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

# Creating 1-D array:

In [4]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr1
arr1.shape

(5,)

## Reshape:

In [8]:
# this will turn (1,5) into (5,1)-> 5 row, 1 column
arr2 = np.reshape(arr1, (5,1))
arr2
arr2.shape

(5, 1)

## Creating 2-D Array:

In [10]:
ar = np.array([[1,2,3,4,5], [6,7,8,9,10]])
ar.shape
print(ar)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
ar1 = np.arange(1,10,2)
ar1
type(ar1)

numpy.ndarray

In [15]:
ar1.reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [16]:
# np - ones:

In [17]:
np.ones((3,3)) # means it will create a 2d array with 3 rows and 3 columns with 1's

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Identity Metrics:

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


## Numpy Vectorized Operation:

In [20]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

In [22]:
# Addition:
add = arr1 + arr2
print(add)

[11 22 33 44 55]


In [23]:
## Element Wise Substraction
print("Substraction:", arr1-arr2)

Substraction: [ -9 -18 -27 -36 -45]


In [24]:
# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

Multiplication: [ 10  40  90 160 250]


In [25]:
# Element-wise division
print("Division:", arr1 / arr2)

Division: [0.1 0.1 0.1 0.1 0.1]


## Universal Function

In [26]:
arr=np.array([2,3,4,5,6])


In [27]:
## square root
print(np.sqrt(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [28]:
## Exponential
print(np.exp(arr))

[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]


In [29]:
## Sine
print(np.sin(arr))

[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [30]:
## natural log
print(np.log(arr))

[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


## Array slicing and Indexing



In [31]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
# Access the first element of the array:

arr[0]

array([1, 2, 3, 4])

In [34]:
arr[0][0]
print(arr[0][0])

1


In [39]:
# Want to extract [7 8 11 12] from the array:

print(arr[1,2:])

[7 8]


In [40]:
print(arr[2,2:])

[11 12]


In [43]:
# now,
#First we need to define rows, then columns to get the desired block:
arr[1:] # start from the second row and go to the end of the rows

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
# Now, focus on the 3nd columns and extract as intended:

arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [45]:
##  Want to extract [3 4 7 8] from the array:

In [46]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
arr[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
arr[0:2, 2:]

array([[3, 4],
       [7, 8]])

## Modify array elements

In [49]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
arr[0,0]=100
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [52]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
arr[1]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [  9  10  11  12]]


## Statistical Concept - Normalization:

In [54]:
# Normalization: mean is 0 and std is 1

data = np.array([1, 2, 3, 4, 5])


In [55]:
# Calculate the mean and standard deviation

mean = np.mean(data)
std =np.std(data)

In [56]:
# Normalize the data

normalized_data = (data - mean) / std
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [57]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


## Logical operation

In [58]:
data=np.array([1,2,3,4,5,6,7,8,9,10])


In [59]:
# I want to retrieve all the data based on my condition:
# That's why we need to use 'indexing'

data[data>5]

array([ 6,  7,  8,  9, 10])

In [63]:
data[(data > 5) & (data < 10)]

array([6, 7, 8, 9])